name: Maven Deploy (Reusable)

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to use'
        required: false
        type: string
        default: '25'
      java-distribution:
        description: 'Java distribution'
        required: false
        type: string
        default: 'temurin'
      deploy-profile:
        description: 'Maven profile for deployment'
        required: false
        type: string
        default: 'ossrh-deploy,artagon-oss-release'
      skip-tests:
        description: 'Skip tests during deployment'
        required: false
        type: boolean
        default: true
      maven-args:
        description: 'Additional Maven arguments'
        required: false
        type: string
        default: ''
    secrets:
      OSSRH_USERNAME:
        description: 'Sonatype OSSRH username'
        required: true
      OSSRH_PASSWORD:
        description: 'Sonatype OSSRH password'
        required: true
      GPG_PRIVATE_KEY:
        description: 'GPG private key for signing'
        required: true
      GPG_PASSPHRASE:
        description: 'GPG passphrase'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: 'maven'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Deploy to OSSRH
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          SKIP_TESTS="${{ inputs.skip-tests && '-DskipTests' || '' }}"
          mvn clean deploy -P${{ inputs.deploy-profile }} $SKIP_TESTS ${{ inputs.maven-args }} \
            -Dgpg.passphrase="$GPG_PASSPHRASE" \
            --batch-mode --no-transfer-progress

      - name: Upload deployment artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: deployed-artifacts
          path: |
            **/target/*.jar
            **/target/*.pom
            **/target/*.asc
          retention-days: 30
